version: 2.1
jobs:
  test-go:
    # Install go modules and run tests
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            mkdir -p test-results
            gotestsum --junitfile test-results/junit.xml
      - store_artifacts:
          path: test-results
          destination: test-results
      - store_test_results:
          path: test-results
  build-go-executables:
    # Build go executables and store them as artifacts
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - run:
          name: Create the ~/artifacts directory if it doesn't exist
          command: mkdir -p ~/artifacts
      - run:
          name: Build executables
          command: go build -o ~/artifacts ./...
      - store_artifacts:
          path: ~/artifacts
          destination: executables
workflows:
  build-and-test:
    jobs:
      - test-go
      - build-go-executables:
          requires:
            - test-go